---
#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    joomla_vhost_dir: "{{php_runtime_meta[ansible_os_family][joomla_webs].vhost_dir}}"
    joomla_vhost_src: "{{php_runtime_meta[ansible_os_family][joomla_webs].vhost_src}}"
    joomla_service: "{{php_runtime_meta[ansible_os_family][joomla_webs].service}}"
    joomla_owner: "{{php_runtime_meta[ansible_os_family][joomla_webs].owner}}"

- debug:
    msg: runtime {{ joomla_vhost_dir }}, {{joomla_vhost_src}}, {{joomla_service}}, {{joomla_owner}}, {{joomla_webs}}, {{ansible_distribution}}

# Joomla  
- name: Remove extra dir
  shell: |
    rm -rf /data/wwwroot/*{{joomla_name}}*

- name: Create folder /data/wwwroot/{{joomla_name}}
  file:
    path: /data/wwwroot/{{joomla_name}}
    state: directory

- name: Download joomla
  unarchive:
    src: "{{joomla_download_url}}"
    dest: /data/wwwroot/joomla
    remote_src: yes

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{joomla_name}}" ]; then mv *{{joomla_name}}* {{joomla_name}}; fi

- name: Preparations for site initialization
  shell: |
    sed -i 's/name="db_user"/&\n\t\t\t\tdefault="{{joomla_name}}"/' database.xml
    sed -i 's/name="db_pass"/&\n\t\t\t\tdefault="{{joomla_db_password}}"/' database.xml
    sed -i 's/name="db_name"/&\n\t\t\t\tdefault="{{joomla_name}}"/' database.xml 
  args:
    chdir: /data/wwwroot/joomla/installation/model/forms

# 系统通用
- name: Permission directory
  shell: |
    find /data/wwwroot -type d -exec chmod 750 {} \;
    find /data/wwwroot -not -type d -exec chmod 640 {} \;

# 根据不同的基础环境分别处理
- block:
  - name: change owner&group
    shell: chown -R {{joomla_owner}}:{{joomla_owner}} /data/wwwroot
    
  - name: restart Apache or Nginx
    service: name={{joomla_service}} state=restarted enabled=yes

  - name: restart php-fpm
    service: name=php-fpm state=restarted
